spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_sync_dev
    username: postgres
    password: postgres
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

transaction-sync:
  privvy:
    api-url: ${PRIVVY_API_URL:}
    email: ${PRIVVY_EMAIL:}
    password: ${PRIVVY_PASSWORD:}

logging:
  level:
    com.transactionsync: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

